spring:    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MaoriLira/microservicesspringcloud
          #user
          #Pass
security:
  basic:
    enabled: true
  user:
    name: mao
    password: mao